# .travis.yml
language: ruby
rvm:
  - 1.9.3
services: postgre
before_script:
  - gem install bundler --pre
  - cp config/database.yml-example config/database.yml
  - rake db:drop
  - rake db:create
  - rake system:bootstrap